Objects And References - Answers and Tests Files
CodingAvenue/codestop-course-php-oop pull request #31
Opened 2020-01-13 06:02 UTC by cerilacanda

2020-04-17 02:05 UTC, TenshiLyle requested changes

2020-04-17 02:05 UTC, TenshiLyle commented on answers/ObjectsAndReferences/28dc6250-a538-4656-9809-c119767c7d0c/MissingNewKeywordTest.php
> +$objectVarC->display();
Let us change the variable names.
```
$person = new Person();
$personRef = $person;
$anotherPersonRef = &$person;
$anotherPersonRef->display();
$person = new Student();
$anotherPersonA->display();
```

2020-04-17 02:05 UTC, TenshiLyle commented on answers/ObjectsAndReferences/28dc6250-a538-4656-9809-c119767c7d0c/MissingNewKeywordTest.php
> +$objectVarC->display();
What is the purpose of `$objectVarB`?

2020-04-17 02:05 UTC, TenshiLyle commented on answers/ObjectsAndReferences/3e23cbe1-3872-4c7c-abf4-67cf15e395c2/IncorrectAmperandPositionTest.php
> +$objectVarA->display();
Same as above.

2020-04-17 02:05 UTC, TenshiLyle commented on answers/ObjectsAndReferences/6a7d9398-bb5b-45f4-a675-534204be8645/IncorrectObjectOperatorTest.php
> +$objectVarA->display();
And this

2020-04-17 02:05 UTC, TenshiLyle commented on answers/ObjectsAndReferences/6d2e5aa8-9b8a-4a37-ad2b-e4229e44579f/MissingDollarSignTest.php
> +$objectVarC->display();
Also this one.

2020-04-17 02:05 UTC, TenshiLyle commented on answers/ObjectsAndReferences/8966cdec-0047-4deb-87a9-ce6b119402c4/MissingSemicolonTest.php
> +$objectVarA->display();
And this one. Please check the rest of the content.

2020-04-17 02:35 UTC, cerilacanda commented on answers/ObjectsAndReferences/28dc6250-a538-4656-9809-c119767c7d0c/MissingNewKeywordTest.php
> +$objectVarC->display();
@TenshiLyle `$objectVarB` in this example shows that it references or points to the same `Person` object that `$objectVarA` does.

> Let us change the variable names.
> 
> ```
> $person = new Person();
> $personRef = $person;
> $anotherPersonRef = &$person;
> $anotherPersonRef->display();
> $person = new Student();
> $anotherPersonA->display();
> ```

This is noted. I will the content related to this one. Thank you.

2020-04-28 15:25 UTC, TenshiLyle approved these changes

2020-04-28 22:53 UTC, merged